services:
  web:
    image: ${ECR_REGISTRY}/hello-php:latest
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: phpuser
      DB_PASS: secret
      DB_NAME: shop
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: shop
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
  
    